spring.application.name=demo







# ===================================================================
# CONFIGURAZIONE POSTGRESQL
# ===================================================================

# URL di connessione: sostituisci 'localhost', '5432' e 'nome_del_tuo_db' con i tuoi dati
spring.datasource.url=jdbc:postgresql://localhost:5432/songslibrary

# Driver JDBC specifico per PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Credenziali di accesso al database
spring.datasource.username=postgres
spring.datasource.password=postgres

# ===================================================================
# CONFIGURAZIONE HIBERNATE / JPA (Opzionale ma consigliata)
# ===================================================================

# Specifica il dialetto SQL corretto per PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Gestione del ciclo di vita del database (DDL)
# Opzioni comuni: update (aggiorna il DB), validate (verifica solo), none (nessuna azione)

# Mostra le query SQL nella console (comodo in fase di sviluppo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=update

# Dimensione massima del singolo file (es. 15 Megabyte)
spring.servlet.multipart.max-file-size=15MB

# Dimensione massima dell'intera richiesta (file + dati di testo complessivi)
spring.servlet.multipart.max-request-size=20MB

logging.file.name=logs/application.log
# Cambia il formato dei log in console (mostra solo HH:mm:ss)
logging.pattern.console=%d{HH:mm:ss} --- [%t] %-40logger{36} : %msg%n
# Cambia il formato dei log nel file su disco
logging.pattern.file=%d{HH:mm:ss} --- [%t] %-40logger{36} : %msg%n